### ISSUE TITLE
Getting Failed to resolve source queue. Error: The specified queue does not exist for this wsdl version.

### ISSUE THREAD

**Issue by 9Balls** [mercury2269/sqsmover#12]
I am receiving this error despite that the queue name exist and name is correct. 

AWS profile is correctly configure and when calling to list sqs using aws cli i got the response correctly.

**Comment by mercury2269** [comment]
Hi there, which AWS region are your queues under? If the queues are not in the default region, `us-west-2`, you would need to specify it via an additional flag `-r`.

**Comment by mercury2269** [comment]
This error message most likely indicates that you don't have a valid region specified. Let me know if it's still a problem.
