### ISSUE TITLE
Getting this error "Failed to un-queue messages to the destination. Error: Batch requests cannot be longer than 262144 bytes. You have sent 866955 bytes."

### ISSUE THREAD

**Issue by yass8n** [mercury2269/sqsmover#13]
• Source queue URL: https://sqs.us-west-1.amazonaws.c...
   • Destination queue URL: https://sqs.us-west-1.amazon...
   • Approximate number of messages in the source queue: 821330
   • Limit is set, will only move 100 messages
   • Starting to move messages...

   ⨯ Failed to un-queue messages to the destination. Error: Batch requests cannot be longer than 262144 bytes. You have sent 866955 bytes.

**Comment by yass8n** [comment]
Here is the command

`sqsmover --source=https://sqs.us-west-1.amazonaws.c... --destination=https://sqs.us-west-1.amazon... --region=us-west-1 --limit=0`

It works fine if I set `--limit=1`. But if I make it  0 or any number greater than 1 it fails with that error

**Comment by mercury2269** [comment]
Hi there! Looks like the batch limit is 256kb and because `sqsmover` tries to move 10 messages with total size of (869kb) at a time without checking total message size, it fails to en-queue.

**Comment by mercury2269** [comment]
Thanks for reporting this problem! If you get latest, I've added a flag to set maximum number of messages in a batch. You could try 
`sqsmover --source=https://sqs.us-west-1.amazonaws.c... --destination=https://sqs.us-west-1.amazon... --region=us-west-1 --batch 1`  or a higher number (possibly 2 in your case), as long as the number of messages in a batch does not exceed 256k total size.

**Comment by yass8n** [comment]
Thank you!
