### ISSUE TITLE
Support for Message Attributes

### ISSUE THREAD

**Issue by d-lorenc** [mercury2269/sqsmover#5]
Moved some messages from DLQ and lost all the Message Attributes. Doesn't look like sqsmover supports Message Attributes yet. Would be a good enhancement.

**Comment by negrusti** [comment]
Same issue for me - lost important attributes this way :(

**Comment by mercury2269** [comment]
> Same issue for me - lost important attributes this way :(

Sorry about that, I'll make sure to add a warning in the readme until I add this feature. Also PRs are welcomed!

**Comment by negrusti** [comment]
@mercury2269 will that work after line 123 in main.go?
			MessageAttributes:            message.MessageAttributes,

**Comment by mercury2269** [comment]
> @mercury2269 will that work after line 123 in main.go?
> MessageAttributes: message.MessageAttributes,
> Or some other changes needed?

Looks like it needs to copy attributes when it converts messages to entries here https://github.com/mercury2269/sqsmover/blob/5c54491eda7fceaab57e908290b2e865ce1222de/main.go#L111

**Comment by negrusti** [comment]
@mercury2269 yes sorry I meant after that line

**Comment by negrusti** [comment]
@d-lorenc @mercury2269 created a pull request, please test. Works for me.

**Comment by negrusti** [comment]
@mercury2269 Thanks! You probably would want to update readme again :)

**Comment by mercury2269** [comment]
Thanks @negrusti !
